= Basic concepts of transactions
:toc:
:toc-title: 事务的基本概念

== 事务的特性
通常来说事务有四大特性：原子性(Atomic)、一致性(Consistency)、隔离性(Isolation)和持久性(Durability)，简称为ACID。

* 原子性：原子性意味着一个事务就像原子一样是不可再分的(在化学反应中)，一个事务就是一个执行单元，事务里面的所有的操作都必须全部执行成功整个事务才会提交，如果其中一个操作失败，那么其它操作也会跟着“连坐”，而一起失败回滚，不可能出现一个事务中部分操作成功，部分操作失败的情况。
* 一致性：初看时，一致两个字可能有些许迷惑，这里的一致并不是指汉语词典中的“相同”，而是“数据正常、正确”，比如：张三向李四转账100RMB，那么李四的账户会增加100RMB，此时如果张三的账户减少了100RMB，那么数据就是正常的，这就达到一致性，如果张三的账户没有减少100RMB，那么数据就不是正常的，这就没有达到一致性；所以一致性指的就是：数据从一个正确的状态转变成另一个正确的状态(也算是种”相同“吧 :) )。
* 隔离性：隔离性意味着，并发执行的事务之间互不”干扰“，一个事务不应该知道其它事务未提交而造成的任何”影响“，比如：两个事务并发执行，事务B进行增加操作，在事务B未提交之前，事务A不应该知道事务B进行的增加操作和增加后的数据，此时事务A查询的数据应该是事务B开启之前的数据，而不是增加后的数据。

    MySQL通过锁和MVCC机制来保证事务的隔离性

* 持久性：持久性意味着，事务一旦提交，数据就不应该再会改变，已提交的事务就像”死去的进程“不应该再对数据有任何影响，而数据会持久化进数据库中。

NOTE: 其中AID都是为了保证C

== 事务的类型

* 扁平事务：扁平事务是现数据库中最简单直接的事务，在MySQL中，一般由 begin 或 start transaction 开启，由 commit 提交结束，或由 rollback 回滚结束；扁平事务就是上述特性中原子性最直接的体现，在扁平事务中，要么所有操作一起成功去提交事务，要么一起失败回滚到起点。

* 带有保存点的扁平事务：扁平事务虽然是最简单的事务，但是它在事务回滚上却”很笨“，它只能回滚到起点，而不能回滚到事务中间的某个位置，这样的事务回滚就会造成一定的资源浪费，因此，带有保存点的扁平事务出现了，这个保存点可以让你在事务回滚时，不直接回滚到起点，而是回滚到这个事务中你定的保存点的位置。语法如下：

    # MySQL
    # 设置保存点
    savepoint [savepoint_name]
    # 回滚到保存点
    rollback [savepoint_name]
    # 删除保存点
    release savepoint [savepoint_name]

* 链式事务：链式事务是在带有保存点的扁平事务的基础上，自动将当前事务的上下文隐式地传递给下一个事务。也就是说，一个事务的提交操作和下一个事务的开始操作具备原子性，上一个事务的处理结果对下一个事务是可见的，事务与事务之间就像链条一样传递下去。

NOTE: 链式事务在提交的时候，会释放要提交的事务中的所有锁和保存点，也就是说，链式事务的回滚操作只能回滚到当前所在事务的保存点，而不能回滚到已提交事务的保存点。

* 嵌套事务：顾名思义，嵌套事务就是有多个事务处于嵌套状态，共同完成一项任务的处理，整个任务具备原子性。嵌套事务最外层有一个顶层事务，这个顶层事务控制着所有的内部子事务，内部子事务提交完成后，整体事务并不会提交，只有最外层的顶层事务提交完成后，整体事务才算提交完成。
** 回滚嵌套事务内部的子事务时，会将事务回滚到外部顶层事务的开始位置。
** 嵌套事务的提交是从内部的子事务向外依次进行的，直到最外层的顶层事务提交完成。
** 回滚嵌套事务最外层的顶层事务时，会回滚嵌套事务包含的所有事务，包括已提交的内部子事务。

    在主流的关系型数据库中，MySQL不支持原生的嵌套事务

* 分布式事务：简单来说，一个分布式事务就是一个整体在不同环境下执行的事务，它可能会有很多相同或不同的子事务分布在不同的环境下执行，只有当所有的子事务执行成功，整个事务才算成功，任何一个子事务失败都会造成整个分布式事务回滚。所以一个分布式事务中事务参与者、事务所在的服务器、涉及的资源服务器以及事务管理器可能都会分布在不同的分布式系统的不同服务或数据库上。例如，在电商系统的下单减库存业务中，订单业务所在的数据库为事务A的节点，库存业务所在的数据库为事务B的节点。事务A和事务B组成了一个具备ACID特性的分布式事务，要么全部提交成功，要么全部提交失败。

== 本地事务
在常见的计算机系统和应用系统中，很多事务是通过关系型数据库进行控制的。这种控制事务的方式是利用数据库本身的事务特性来实现，而在这种实现方式中，数据库和应用通常会被放在同一台服务器中，因此，这种基于关系型数据库的事务也可以称作本地事务或者传统事务

本地事务的优缺点::

优点:::
* 支持严格的ACID特性，这也是本地事务得以实现的基础。
* 事务可靠，一般不会出现异常情况。
* 本地事务的执行效率比较高。
* 事务的状态可以只在数据库中进行维护，上层的应用不必理会事务的具体状态。
* 应用的编程模型比较简单，不会涉及复杂的网络通信。

缺点:::
* 不具备分布式事务的处理能力。
* 一次事务过程中只能连接一个支持事务的数据库，即不能用于多个事务性数据库。

== MySQL事务基础
数据库一般会并发执行事务，而并发执行事务就可能会对相同数据进行增删查改，从而引发一系列问题；MySQL中并发执行事务可能会带来如下问题：(更新丢失)脏写、脏读、不可重复读和幻读。

(更新丢失)脏写::

脏读::

不可重复读::

幻读::

//

== 小结
